// examples/react/src/App.tsx
/**
 * Example DApp (React) — demo integration with the Antarctic Wallet SDK.
 *
 * The entire flow lives in one file: types → helpers → SDK init → operations → UI.
 * Standalone run: http://localhost:5175
 * When embedded: the wallet loads this app inside an iframe and passes its
 * origin via the ?parentOrigin=... query parameter.
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import {
  AWSDK,
  AWCommand,
  AWInitError,
  AWOperationError,
  AWScopeError,
  AWSessionError,
  AWTimeoutError,
} from '@antarctic-wallet/aw-sdk';
import type {
  AWOperationType,
  AWSession,
  AWUserContext,
} from '@antarctic-wallet/aw-sdk';

// ── Types ───────────────────────────────────────────────────────────────────

/** App configuration loaded from public/config.json */
interface AppConfig {
  id: string;
  name: string;
  requiredScopes: string[];
}

/** Single Event Log entry — renders in the log panel in real time */
interface LogEntry {
  time: string;
  message: string;
  type: 'info' | 'success' | 'error' | 'warn';
}

/** SDK lifecycle: idle → connecting → ready (or error) */
type AppStatus = 'idle' | 'connecting' | 'ready' | 'error';

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Resolves the parent window (wallet) origin for the postMessage channel.
 * Resolution order:
 *   1. ?parentOrigin=... — explicit override via query
 *   2. document.referrer — auto-detected when running inside an iframe
 *   3. localhost wallet dev-server fallback
 */
function getParentOrigin(): string {
  const params = new URLSearchParams(window.location.search);
  const fromParam = params.get('parentOrigin');
  if (fromParam) return fromParam;
  if (window.parent !== window && document.referrer) {
    try {
      return new URL(document.referrer).origin;
    } catch {
      //
    }
  }
  return 'https://localhost:3310';
}

/**
 * Normalises any SDK error into a human-readable string for the log.
 * Demonstrates how to work with every typed SDK error class.
 */
function handleSdkError(error: unknown): string {
  if (error instanceof AWOperationError) {
    return `Operation error [${error.errorCode}]: ${error.message} (opId: ${error.operationId})`;
  }
  if (error instanceof AWInitError) return `Init error [${error.errorCode}]: ${error.message}`;
  if (error instanceof AWSessionError) return `Session error [${error.errorCode}]: ${error.message}`;
  if (error instanceof AWScopeError) return `Scope error [${error.errorCode}]: ${error.message}`;
  if (error instanceof AWTimeoutError) return `Timeout: ${error.message}`;
  if (error instanceof Error) return error.message;
  return String(error);
}

/** SDK commands used to probe version support via sdk.isCommandAvailable() */
const KNOWN_COMMANDS: { name: string; cmd: AWCommand }[] = [
  { name: 'Init', cmd: AWCommand.Init },
  { name: 'SessionRefresh', cmd: AWCommand.SessionRefresh },
  { name: 'PrepareOperation', cmd: AWCommand.PrepareOperation },
  { name: 'RequestConfirm', cmd: AWCommand.RequestConfirm },
  { name: 'GetSessionStatus', cmd: AWCommand.GetSessionStatus },
  { name: 'GetScopes', cmd: AWCommand.GetScopes },
  { name: 'GetScopesData', cmd: AWCommand.GetScopesData },
];

// ── Component ───────────────────────────────────────────────────────────────

export function App() {
  const [config, setConfig] = useState<AppConfig | null>(null);
  const [status, setStatus] = useState<AppStatus>('idle');
  const [session, setSession] = useState<AWSession | null>(null);
  const [user, setUser] = useState<AWUserContext | null>(null);
  const [insideWallet, setInsideWallet] = useState(false);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [busy, setBusy] = useState<string | null>(null);

  const sdkRef = useRef<AWSDK | null>(null);
  const logRef = useRef<HTMLDivElement>(null);

  const addLog = useCallback((message: string, type: LogEntry['type'] = 'info') => {
    setLogs((prev) => [...prev, { time: new Date().toLocaleTimeString(), message, type }]);
  }, []);

  useEffect(() => {
    if (logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight;
  }, [logs]);

  /**
   * Full SDK bootstrap — runs once on mount:
   *   1. Detect whether we're embedded inside the wallet (isInsideWallet)
   *   2. Load public/config.json with appId and requiredScopes
   *   3. Create the AWSDK instance with debug/retry/persistSession
   *   4. Subscribe to every SDK event (ready/error/scopes/session/operation)
   *   5. sdk.init() — handshake with the host over postMessage
   */
  useEffect(() => {
    let destroyed = false;
    setInsideWallet(AWSDK.isInsideWallet());
    addLog(`isInsideWallet: ${AWSDK.isInsideWallet()}`);

    (async () => {
      const cfg: AppConfig = await fetch('./config.json').then((r) => r.json());
      if (destroyed) return;
      setConfig(cfg);

      const sdk = new AWSDK({
        appId: cfg.id,
        scopes: [...cfg.requiredScopes],
        parentOrigin: getParentOrigin(),
        debug: true,
        timeout: 30_000,
        persistSession: true,
        retry: { maxAttempts: 3, baseDelay: 1000 },
      });
      sdkRef.current = sdk;

      // Handshake finished — session token and userContext are available
      sdk.events.on('sdk.ready', (s: AWSession) => {
        addLog('SDK ready!', 'success');
        setStatus('ready');
        setSession(s);
        setUser(s.userContext ?? null);
      });

      // Fatal SDK error (init failed, host unreachable, etc.)
      sdk.events.on('sdk.error', ({ code, message }) => {
        addLog(`SDK error: [${code}] ${message}`, 'error');
        setStatus('error');
      });

      // User approved additional scopes
      sdk.events.on('scopes.granted', ({ scopes }) =>
        addLog(`Scopes granted: ${scopes.join(', ')}`, 'success'),
      );

      // Session token rotated (auto-refresh or explicit refreshSession())
      sdk.events.on('session.refreshed', ({ sessionToken, expiresAt }) => {
        addLog(`Session refreshed, expires: ${new Date(expiresAt).toLocaleTimeString()}`);
        setSession((prev) => (prev ? { ...prev, sessionToken, expiresAt } : prev));
      });

      // Session expired — re-initialisation is required
      sdk.events.on('session.expired', () => {
        addLog('Session expired!', 'warn');
        setStatus('error');
        setSession(null);
        setUser(null);
      });

      // User declined to confirm the operation in the wallet UI
      sdk.events.on('operation.rejected', ({ operationId, reason }) =>
        addLog(`Operation ${operationId} rejected: ${reason}`, 'warn'),
      );

      addLog('Initializing SDK...');
      setStatus('connecting');
      try {
        await sdk.init();
      } catch (error) {
        if (destroyed) return;
        addLog(`Init failed: ${handleSdkError(error)}`, 'error');
        setStatus('error');
      }
    })();

    return () => {
      destroyed = true;
      sdkRef.current?.destroy();
      sdkRef.current = null;
    };
  }, [addLog]);

  // ── Actions ──────────────────────────────────────────────────────────────

  /**
   * Shared runner for every user-facing operation.
   * Flow: prepare() creates an intent → requestConfirmation() asks the user
   * to approve it in the wallet UI → the awaited result contains status/txId.
   */
  async function runOperation(
    key: string,
    label: string,
    params: Parameters<AWSDK['operations']['prepare']>[0],
  ) {
    const sdk = sdkRef.current;
    if (!sdk) return;
    setBusy(key);
    addLog(`Preparing ${label} intent...`);
    try {
      const intent = await sdk.operations.prepare(params);
      addLog(`${label} intent prepared: ${intent.operationId} (${intent.status})`);
      addLog('Requesting user confirmation...');
      const result = await sdk.operations.requestConfirmation(intent.operationId);
      addLog(
        `${label} result: ${result.status}${result.txId ? `, txId: ${result.txId}` : ''}`,
        'success',
      );
    } catch (error) {
      addLog(`${label} failed: ${handleSdkError(error)}`, 'error');
    } finally {
      setBusy(null);
    }
  }

  /** Pay 5 USDT — prepares a payment intent and asks the user to confirm */
  const pay = () =>
    runOperation('pay', 'Pay', {
      type: 'pay' as AWOperationType,
      amount: '5.00',
      currency: 'USDT',
      to: 'TRTNGawnjNjqaWrMUFCHfBJFuaxaXx1Ntk',
      description: 'Test payment from Example DApp',
      metadata: { orderId: 'demo-001' },
    });

  /** Request a 10 USDT deposit to this app's wallet address */
  const receive = () =>
    runOperation('receive', 'Receive', {
      type: 'receive' as AWOperationType,
      amount: '10.00',
      currency: 'USDT',
      to: '',
      description: 'Request deposit from Example DApp',
    });

  /** Request additional scopes (balance, pay) beyond the ones declared in config */
  const requestScopes = () =>
    runOperation('scopes', 'Scopes', {
      type: 'scopes' as AWOperationType,
      amount: '0',
      currency: 'USDT',
      to: '',
      description: 'Request additional scopes',
      metadata: { scopes: ['balance', 'pay'] },
    });

  /** Force-rotate the session token ahead of its expiry */
  async function refresh() {
    const sdk = sdkRef.current;
    if (!sdk) return;
    setBusy('refresh');
    try {
      await sdk.refreshSession();
      addLog('Session refreshed successfully', 'success');
    } catch (error) {
      addLog(`Refresh failed: ${handleSdkError(error)}`, 'error');
    } finally {
      setBusy(null);
    }
  }

  /** Query the wallet for authoritative session status and granted scopes */
  async function checkStatus() {
    const sdk = sdkRef.current;
    if (!sdk) return;
    setBusy('status');
    try {
      const r = await sdk.status();
      addLog(
        `Status: ${r.status}, expires: ${new Date(r.expiresAt).toLocaleTimeString()}, scopes: [${r.grantedScopes.join(', ')}]`,
        'success',
      );
    } catch (error) {
      addLog(`Status check failed: ${handleSdkError(error)}`, 'error');
    } finally {
      setBusy(null);
    }
  }

  /** List the scopes currently granted to this app */
  async function getScopes() {
    const sdk = sdkRef.current;
    if (!sdk) return;
    try {
      const scopes = await sdk.scopes.getScopes();
      addLog(`Granted scopes: [${scopes.join(', ')}]`, 'success');
    } catch (error) {
      addLog(`Get scopes failed: ${handleSdkError(error)}`, 'error');
    }
  }

  /** Fetch the payload exposed by each granted scope (e.g. balance, user data) */
  async function getScopeData() {
    const sdk = sdkRef.current;
    if (!sdk) return;
    try {
      const data = await sdk.scopes.getData();
      addLog(`Scope data: ${JSON.stringify(data)}`, 'success');
    } catch (error) {
      addLog(`Get scope data failed: ${handleSdkError(error)}`, 'error');
    }
  }

  /** Probe each known SDK command for version support on the current host */
  function checkCommands() {
    const sdk = sdkRef.current;
    if (!sdk) return;
    for (const { name, cmd } of KNOWN_COMMANDS) {
      const ok = sdk.isCommandAvailable(cmd);
      addLog(`${name}: ${ok ? 'available' : 'not available'}`, ok ? 'success' : 'warn');
    }
  }

  // ── UI ───────────────────────────────────────────────────────────────────

  const disabled = !session;

  return (
    <div className="app">
      <header className="header">
        <h1 className="header__title">{config?.name ?? 'Loading...'}</h1>
        <div className="header__badges">
          <span className={insideWallet ? 'badge -inside' : 'badge -outside'}>
            {insideWallet ? 'In Wallet' : 'Standalone'}
          </span>
          <span className={`status-dot -${status}`} />
          <span className="status-label">{status}</span>
        </div>
      </header>

      {user && (
        <section className="panel">
          <div className="user">
            {user.avatarUrl && <img src={user.avatarUrl} alt="" className="user__avatar" />}
            <div>
              {user.displayName && <div className="user__name">{user.displayName}</div>}
              {user.walletAddress && <div className="user__wallet">{user.walletAddress}</div>}
              {user.userId && <div className="user__id">ID: {user.userId}</div>}
            </div>
          </div>
        </section>
      )}

      {session && (
        <section className="panel">
          <div className="panel__title">Session</div>
          <div className="info-grid">
            <span className="info-grid__label">Token</span>
            <span className="info-grid__value">{session.sessionToken.slice(0, 20)}...</span>
            <span className="info-grid__label">Expires</span>
            <span className="info-grid__value">
              {new Date(session.expiresAt).toLocaleTimeString()}
            </span>
          </div>
          <div className="scopes">
            {session.grantedScopes.map((s) => (
              <span key={s} className="scope-chip">
                {s}
              </span>
            ))}
          </div>
        </section>
      )}

      <div className="actions-grid">
        <section className="panel">
          <div className="panel__title">Operations</div>
          <button className="btn -accent" disabled={disabled || busy === 'scopes'} onClick={requestScopes}>
            {busy === 'scopes' ? '...' : 'Request Scopes'}
          </button>
          <button className="btn -accent" disabled={disabled || busy === 'pay'} onClick={pay}>
            {busy === 'pay' ? '...' : 'Pay 5 USDT'}
          </button>
          <button className="btn -accent" disabled={disabled || busy === 'receive'} onClick={receive}>
            {busy === 'receive' ? '...' : 'Receive 10 USDT'}
          </button>
        </section>

        <section className="panel">
          <div className="panel__title">Session</div>
          <button className="btn -ghost" disabled={disabled || busy === 'refresh'} onClick={refresh}>
            Refresh
          </button>
          <button className="btn -ghost" disabled={disabled || busy === 'status'} onClick={checkStatus}>
            Check Status
          </button>
        </section>

        <section className="panel">
          <div className="panel__title">Scopes</div>
          <button className="btn -ghost" disabled={disabled} onClick={getScopes}>
            Get Scopes
          </button>
          <button className="btn -ghost" disabled={disabled} onClick={getScopeData}>
            Get Scope Data
          </button>
        </section>

        <section className="panel">
          <div className="panel__title">Commands</div>
          <button className="btn -ghost" disabled={disabled} onClick={checkCommands}>
            Check Available
          </button>
        </section>
      </div>

      <section className="panel">
        <div className="panel__title">Event Log</div>
        <div ref={logRef} className="log">
          {logs.map((e, i) => (
            <div key={i} className={`log__line -${e.type}`}>
              <span className="log__time">[{e.time}]</span> {e.message}
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

// examples/basic/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from 'vue';
import {
  AWSDK,
  AWScope,
  AWCommand,
  AWInitError,
  AWOperationError,
  AWScopeError,
  AWSessionError,
  AWTimeoutError,
} from '@antarctic-wallet/aw-sdk';
import type { AWSession, AWUserContext } from '@antarctic-wallet/aw-sdk';

interface AppConfig {
  id: string;
  name: string;
  shortDescription: string;
  description: string;
  icon: string;
  category: string;
  requiredScopes: string[];
}

interface LogEntry {
  time: string;
  message: string;
  type: 'info' | 'success' | 'error' | 'warn';
}

const appConfig = ref<AppConfig | null>(null);
const status = ref<'idle' | 'connecting' | 'ready' | 'error'>('idle');
const statusText = ref('Idle');
const session = ref<AWSession | null>(null);
const user = ref<AWUserContext | null>(null);
const insideWallet = ref(false);
const logs = ref<LogEntry[]>([]);
const transferring = ref(false);
const paying = ref(false);
const refreshing = ref(false);
const checkingStatus = ref(false);
const loadingScopes = ref(false);
const loadingScopeData = ref(false);
const logContainer = ref<HTMLElement | null>(null);

let sdk: AWSDK | null = null;

function addLog(message: string, type: LogEntry['type'] = 'info') {
  const time = new Date().toLocaleTimeString();
  logs.value.push({ time, message, type });
  nextTick(() => {
    if (logContainer.value) {
      logContainer.value.scrollTop = logContainer.value.scrollHeight;
    }
  });
}

function setStatus(s: typeof status.value, text: string) {
  status.value = s;
  statusText.value = text;
}

function getParentOrigin(): string {
  const params = new URLSearchParams(window.location.search);
  const fromParam = params.get('parentOrigin');
  if (fromParam) {
    return fromParam;
  }

  if (window.parent !== window) {
    try {
      const referrer = document.referrer;
      if (referrer) {
        const url = new URL(referrer);
        return url.origin;
      }
    } catch {
      //
    }
  }

  return 'https://localhost:3310';
}

/**
 * Типизированная обработка ошибок SDK — демонстрирует все классы ошибок
 */
function handleSdkError(error: unknown): string {
  if (error instanceof AWOperationError) {
    return `Operation error [${error.errorCode}]: ${error.message} (opId: ${error.operationId})`;
  }
  if (error instanceof AWInitError) {
    return `Init error [${error.errorCode}]: ${error.message}`;
  }
  if (error instanceof AWSessionError) {
    return `Session error [${error.errorCode}]: ${error.message}`;
  }
  if (error instanceof AWScopeError) {
    return `Scope error [${error.errorCode}]: ${error.message}`;
  }
  if (error instanceof AWTimeoutError) {
    return `Timeout: ${error.message}`;
  }
  if (error instanceof Error) {
    return error.message;
  }
  return String(error);
}

// ── Operations ──────────────────────────────────────────────────────────────

async function handleTransfer() {
  if (!sdk) return;
  transferring.value = true;
  addLog('Preparing transfer operation...');

  try {
    const intent = await sdk.operations.prepare({
      type: 'transfer',
      amount: '10.00',
      currency: 'USDT',
      to: 'UQBvW8Z5huBkMJYdnfAEM5JqTNQXGbE1...',
      description: 'Test transfer from Example DApp',
    });
    addLog(`Transfer prepared: ${intent.operationId} (${intent.status})`, 'info');

    addLog('Requesting user confirmation...');
    const result = await sdk.operations.requestConfirmation(intent.operationId);
    addLog(`Transfer result: ${result.status}, txId: ${result.txId}`, 'success');
  } catch (error) {
    addLog(`Transfer failed: ${handleSdkError(error)}`, 'error');
  } finally {
    transferring.value = false;
  }
}

async function handlePayment() {
  if (!sdk) return;
  paying.value = true;
  addLog('Preparing payment operation...');

  try {
    const intent = await sdk.operations.prepare({
      type: 'payment',
      amount: '5.00',
      currency: 'USDT',
      to: 'UQDrjaLahLkMB-hMCmkzOyBuHJ186Kf3...',
      description: 'Test payment from Example DApp',
      metadata: { orderId: 'demo-001', item: 'Premium Plan' },
    });
    addLog(`Payment prepared: ${intent.operationId} (${intent.status})`, 'info');

    addLog('Requesting user confirmation...');
    const result = await sdk.operations.requestConfirmation(intent.operationId);
    addLog(`Payment result: ${result.status}, txId: ${result.txId}`, 'success');
  } catch (error) {
    addLog(`Payment failed: ${handleSdkError(error)}`, 'error');
  } finally {
    paying.value = false;
  }
}

// ── Session ─────────────────────────────────────────────────────────────────

async function handleRefresh() {
  if (!sdk) return;
  refreshing.value = true;
  addLog('Refreshing session...');

  try {
    await sdk.refreshSession();
    addLog('Session refreshed successfully', 'success');
  } catch (error) {
    addLog(`Refresh failed: ${handleSdkError(error)}`, 'error');
  } finally {
    refreshing.value = false;
  }
}

async function handleCheckStatus() {
  if (!sdk) return;
  checkingStatus.value = true;
  addLog('Checking session status...');

  try {
    const result = await sdk.status();
    addLog(
      `Status: ${result.status}, expires: ${new Date(result.expiresAt).toLocaleTimeString()}, scopes: [${result.grantedScopes.join(', ')}]`,
      'success',
    );
  } catch (error) {
    addLog(`Status check failed: ${handleSdkError(error)}`, 'error');
  } finally {
    checkingStatus.value = false;
  }
}

function handleGetSession() {
  if (!sdk) return;
  const current = sdk.getSession();
  if (current) {
    addLog(
      `getSession → token: ${current.sessionToken.slice(0, 12)}..., scopes: [${current.grantedScopes.join(', ')}], expires: ${new Date(current.expiresAt).toLocaleTimeString()}`,
      'success',
    );
  } else {
    addLog('getSession → null (not initialized)', 'warn');
  }
}

// ── Scopes ──────────────────────────────────────────────────────────────────

async function handleGetScopes() {
  if (!sdk) return;
  loadingScopes.value = true;
  addLog('Requesting granted scopes...');

  try {
    const scopes = await sdk.scopes.getScopes();
    addLog(`Granted scopes: [${scopes.join(', ')}]`, 'success');
  } catch (error) {
    addLog(`Get scopes failed: ${handleSdkError(error)}`, 'error');
  } finally {
    loadingScopes.value = false;
  }
}

async function handleGetScopeData() {
  if (!sdk) return;
  loadingScopeData.value = true;
  addLog('Requesting scope data...');

  try {
    const data = await sdk.scopes.getData();
    addLog(`Scope data: ${JSON.stringify(data)}`, 'success');
  } catch (error) {
    addLog(`Get scope data failed: ${handleSdkError(error)}`, 'error');
  } finally {
    loadingScopeData.value = false;
  }
}

// ── Commands ────────────────────────────────────────────────────────────────

function handleCheckCommands() {
  if (!sdk) return;
  const commands: { name: string; cmd: AWCommand }[] = [
    { name: 'Init', cmd: AWCommand.Init },
    { name: 'SessionRefresh', cmd: AWCommand.SessionRefresh },
    { name: 'PrepareOperation', cmd: AWCommand.PrepareOperation },
    { name: 'RequestConfirm', cmd: AWCommand.RequestConfirm },
    { name: 'GetSessionStatus', cmd: AWCommand.GetSessionStatus },
    { name: 'GetScopes', cmd: AWCommand.GetScopes },
    { name: 'GetScopesData', cmd: AWCommand.GetScopesData },
  ];

  for (const { name, cmd } of commands) {
    const available = sdk.isCommandAvailable(cmd);
    addLog(`${name}: ${available ? 'available' : 'not available'}`, available ? 'success' : 'warn');
  }
}

// ── Lifecycle ───────────────────────────────────────────────────────────────

onMounted(async () => {
  // Static check — works before SDK init
  insideWallet.value = AWSDK.isInsideWallet();
  addLog(`isInsideWallet: ${insideWallet.value}`, 'info');

  try {
    const res = await fetch('/config.json');
    appConfig.value = await res.json();
  } catch (error) {
    addLog(`Failed to load config: ${handleSdkError(error)}`, 'error');
    setStatus('error', 'Config Error');
    return;
  }

  const config = appConfig.value!;

  // Full SDK config with all options
  sdk = new AWSDK({
    appId: config.id,
    scopes: [...config.requiredScopes],
    parentOrigin: getParentOrigin(),
    debug: true,
    timeout: 30_000,
    persistSession: true,
    retry: {
      maxAttempts: 3,
      baseDelay: 1000,
    },
  });

  // ── Events ──────────────────────────────────────────────────────────────

  sdk.events.on('sdk.ready', (s: AWSession) => {
    addLog('SDK ready!', 'success');
    setStatus('ready', 'Connected');
    session.value = s;
    user.value = s.userContext ?? null;

    if (s.userContext?.displayName) {
      addLog(`User: ${s.userContext.displayName}`, 'info');
    }
    if (s.userContext?.walletAddress) {
      addLog(`Wallet: ${s.userContext.walletAddress}`, 'info');
    }
  });

  sdk.events.on('sdk.error', ({ code, message }: { code: string; message: string }) => {
    addLog(`SDK error: [${code}] ${message}`, 'error');
    setStatus('error', 'Error');
  });

  sdk.events.on('scopes.granted', ({ scopes }: { scopes: string[] }) => {
    addLog(`Scopes granted: ${scopes.join(', ')}`, 'success');
  });

  sdk.events.on('session.refreshed', ({ sessionToken, expiresAt }: { sessionToken: string; expiresAt: number }) => {
    addLog(`Session refreshed, expires: ${new Date(expiresAt).toLocaleTimeString()}`, 'info');
    if (session.value) {
      session.value = { ...session.value, sessionToken, expiresAt };
    }
  });

  sdk.events.on('session.expired', () => {
    addLog('Session expired!', 'warn');
    setStatus('error', 'Expired');
    session.value = null;
    user.value = null;
  });

  sdk.events.on('operation.rejected', ({ operationId, reason }: { operationId: string; reason: string }) => {
    addLog(`Operation ${operationId} rejected: ${reason}`, 'warn');
  });

  // ── Init ────────────────────────────────────────────────────────────────

  addLog('Initializing SDK...');
  setStatus('connecting', 'Connecting...');

  try {
    await sdk.init();
  } catch (error) {
    addLog(`Init failed: ${handleSdkError(error)}`, 'error');
    setStatus('error', 'Init Failed');
  }
});

onUnmounted(() => {
  sdk?.destroy();
});
</script>

<template>
  <div class="app-container">
    <!-- Info Card -->
    <div class="card">
      <div class="card-header">
        <div class="card-title">{{ appConfig?.name ?? 'Loading...' }}</div>
        <span class="env-badge" :class="insideWallet ? 'inside' : 'outside'">
          {{ insideWallet ? 'In Wallet' : 'Standalone' }}
        </span>
      </div>
      <span class="status-badge" :class="status">{{ statusText }}</span>

      <div v-if="user" class="user-section">
        <img v-if="user.avatarUrl" :src="user.avatarUrl" class="user-avatar" alt="avatar" />
        <div class="user-info">
          <div v-if="user.displayName" class="user-name">{{ user.displayName }}</div>
          <div v-if="user.walletAddress" class="user-wallet">{{ user.walletAddress }}</div>
          <div v-if="user.userId" class="user-id">ID: {{ user.userId }}</div>
        </div>
      </div>

      <div v-if="session">
        <div class="info-row">
          <span class="info-label">Token</span>
          <span class="info-value">{{ session.sessionToken.slice(0, 20) }}...</span>
        </div>
        <div class="info-row">
          <span class="info-label">Expires</span>
          <span class="info-value">{{ new Date(session.expiresAt).toLocaleTimeString() }}</span>
        </div>
        <div>
          <div class="info-row">
            <span class="info-label">Scopes</span>
          </div>
          <div class="scopes-list">
            <span v-for="scope in session.grantedScopes" :key="scope" class="scope-tag">
              {{ scope }}
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Operations Card -->
    <div class="card">
      <div class="card-title">Operations</div>
      <button
        class="btn btn-primary"
        :disabled="!session || transferring"
        @click="handleTransfer"
      >
        {{ transferring ? 'Sending...' : 'Send Transfer (10 USDT)' }}
      </button>
      <button
        class="btn btn-primary"
        :disabled="!session || paying"
        @click="handlePayment"
      >
        {{ paying ? 'Paying...' : 'Send Payment (5 USDT)' }}
      </button>
    </div>

    <!-- Session Card -->
    <div class="card">
      <div class="card-title">Session</div>
      <button
        class="btn btn-secondary"
        :disabled="!session || refreshing"
        @click="handleRefresh"
      >
        {{ refreshing ? 'Refreshing...' : 'Refresh Session' }}
      </button>
      <button
        class="btn btn-secondary"
        :disabled="!session || checkingStatus"
        @click="handleCheckStatus"
      >
        {{ checkingStatus ? 'Checking...' : 'Check Session Status' }}
      </button>
      <button
        class="btn btn-secondary"
        :disabled="!sdk"
        @click="handleGetSession"
      >
        Get Session
      </button>
    </div>

    <!-- Scopes Card -->
    <div class="card">
      <div class="card-title">Scopes</div>
      <button
        class="btn btn-secondary"
        :disabled="!session || loadingScopes"
        @click="handleGetScopes"
      >
        {{ loadingScopes ? 'Loading...' : 'Get Scopes' }}
      </button>
      <button
        class="btn btn-secondary"
        :disabled="!session || loadingScopeData"
        @click="handleGetScopeData"
      >
        {{ loadingScopeData ? 'Loading...' : 'Get Scope Data' }}
      </button>
    </div>

    <!-- Commands Card -->
    <div class="card">
      <div class="card-title">Command Versioning</div>
      <button
        class="btn btn-secondary"
        :disabled="!session"
        @click="handleCheckCommands"
      >
        Check Available Commands
      </button>
    </div>

    <!-- Event Log Card -->
    <div class="card">
      <div class="card-title">Event Log</div>
      <div ref="logContainer" class="log-container">
        <div v-for="(entry, i) in logs" :key="i" class="log-entry" :class="entry.type">
          [{{ entry.time }}] {{ entry.message }}
        </div>
      </div>
    </div>
  </div>
</template>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f5f6f8;
  color: #1a1a2e;
}
</style>

<style scoped>
.app-container {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f5f6f8;
  color: #1a1a2e;
  padding: 16px;
  min-height: 100vh;
  max-width: 400px;
  margin: 0 auto;
}

.card {
  background: white;
  border-radius: 16px;
  padding: 20px;
  margin-bottom: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}

.card-header .card-title {
  margin-bottom: 0;
}

.card-title {
  font-size: 18px;
  font-weight: 600;
  margin-bottom: 12px;
}

.env-badge {
  padding: 3px 8px;
  border-radius: 6px;
  font-size: 11px;
  font-weight: 600;
}

.env-badge.inside { background: #d4edda; color: #155724; }
.env-badge.outside { background: #fff3cd; color: #856404; }

.status-badge {
  display: inline-block;
  padding: 4px 12px;
  border-radius: 20px;
  font-size: 12px;
  font-weight: 600;
  margin-bottom: 12px;
}

.status-badge.idle { background: #e9eaee; color: #6b6b77; }
.status-badge.connecting { background: #fff3cd; color: #856404; }
.status-badge.ready { background: #d4edda; color: #155724; }
.status-badge.error { background: #f8d7da; color: #721c24; }

.user-section {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px 0;
  border-bottom: 1px solid #f0f0f0;
  margin-bottom: 4px;
}

.user-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  object-fit: cover;
}

.user-info {
  min-width: 0;
}

.user-name {
  font-size: 15px;
  font-weight: 600;
}

.user-wallet {
  font-size: 12px;
  color: #6b6b77;
  word-break: break-all;
}

.user-id {
  font-size: 11px;
  color: #9b9baa;
}

.info-row {
  display: flex;
  justify-content: space-between;
  padding: 8px 0;
  border-bottom: 1px solid #f0f0f0;
  font-size: 14px;
}

.info-row:last-child {
  border-bottom: none;
}

.info-label {
  color: #6b6b77;
}

.info-value {
  color: #1a1a2e;
  font-weight: 500;
  text-align: right;
  max-width: 60%;
  word-break: break-all;
}

.btn {
  width: 100%;
  padding: 14px;
  border: none;
  border-radius: 12px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: opacity 0.2s;
  margin-bottom: 8px;
}

.btn:last-child {
  margin-bottom: 0;
}

.btn:active { opacity: 0.8; }
.btn:disabled { opacity: 0.5; cursor: not-allowed; }

.btn-primary { background: #0075ff; color: white; }
.btn-secondary { background: #e9eaee; color: #1a1a2e; }

.log-container {
  background: #1a1a2e;
  border-radius: 12px;
  padding: 12px;
  max-height: 200px;
  overflow-y: auto;
  font-family: 'Menlo', 'Monaco', monospace;
  font-size: 11px;
  line-height: 1.6;
}

.log-entry {
  color: #b0b0b0;
}

.log-entry.info { color: #7cb2fd; }
.log-entry.success { color: #01c167; }
.log-entry.error { color: #ff6b6b; }
.log-entry.warn { color: #ffc107; }

.scopes-list {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 8px;
}

.scope-tag {
  background: #eef0ff;
  color: #0075ff;
  padding: 4px 10px;
  border-radius: 8px;
  font-size: 12px;
  font-weight: 500;
}
</style>
